### ISSUE TITLE
Remove runtime dependency on Core.Map? (Was: Cannot Marshal Tdigest.t?)

### ISSUE THREAD

**Issue by cemerick** [SGrondin/tdigest#2]
e.g.

```
utop # let k = Tdigest.create () |> Tdigest.add_list [1.; 2.; 3.];;
val k : Tdigest.t = <abstr>
utop # Marshal.to_string k [];;
Exception: Invalid_argument "output_value: functional value".
```

...which seems bizarre to me, since AFAICT `Tdigest.t` doesn't hold any functions?? :thinking:

**Comment by cemerick** [comment]
It was brought to my attention that the `Float.Map` being used here are of the Jane Street variety, and so they hold a record of the comparison function necessary for its implementation (vs stdlib functor-based maps that don't). Sorry for the noise insofar as I didn't notice that at first.

Since the JS Map isn't part of the Tdigest API, would you be at all open to a patch that swapped it for a stdlib map? It looks like the only bit that would need to be backfilled would be a `binary_search` impl.

(I'll also update the subject of the issue to suit the suggestion here.)

**Comment by SGrondin** [comment]
Yeah I'm only using Core for `Map.binary_search`. I've been wanting to remove the dependency for some time. I'll work on it in the next week or two.

**Comment by SGrondin** [comment]
Good detective work. The workaround is `Tdigest.sexp_of_t` to get a marshallable type. It will generate a very compact string. Performance should be sufficient for most use cases. Please let me know if that doesn't work for you.

**Comment by cemerick** [comment]
Yeah, the sexp workaround isn't great, insofar as I'm not actually aiming to marshal just tdigests, but a much, much larger composite structure that would ideally hold a bunch of tdigests in various places within it. In this case, the workaround is probably to either:

* make the types of such slots `Tdigest.t option ref`, so I can sexp-serialize all of my digests and set their originating refs to None, and likewise rehydrate an un-marshalled structure with its digests
* stop using `Marshal` (an improvement in principle, but something that's continued to be not-a-priority for years now since Marshal does do a darn good job for what I need it for, at least up to now).

Of course, I much prefer your original reply (:wink:), but I understand your not necessarily wanting to commit to a change.

**Comment by SGrondin** [comment]
Haha yeah I still want to remove the dependency on Core. I might be able to get to it this weekend or the next one, no promises. I don't think your situation is unique.

**Comment by SGrondin** [comment]
My first attempt, by recreating the `Stdlib.Map` module and adding Core's `binary_search`, resulted in a 11x slowdown of `add`/`add_list` operations.

I've got another version I'm working on that's both simpler and I think will be ""only"" 8x slower. I then plan on offering both versions: the normal fast non-marshallable version by default, and the slower marshallable version as alternative.

**Comment by SGrondin** [comment]
Now just waiting for https://github.com/ocaml/opam-repository/pull/24351

Just replace all the function calls from `Tdigest.*` to `Tdigest.Marshallable.*` in your code and it will work as expected! It's about 5x slower, but that's still twice as fast as my first attempt using a modified version of the standard library maps.

**Comment by SGrondin** [comment]
It's available on OPAM now: `tdigest.2.1.3`

---

@jvillard It can be serialized now. I remembered your [commit message](https://github.com/facebook/infer/commit/b1284587e56d95c81ebdd856894563c335fffa83):
> - tdigest's datastructure cannot be serialised by Marshal, so we need a
  bit more work in Stats.ml before we send the final results over to the
  orchestrating process

**Comment by jvillard** [comment]
> It's available on OPAM now: `tdigest.2.1.3`
> 
> @jvillard It can be serialized now. I remembered your [commit message](https://github.com/facebook/infer/commit/b1284587e56d95c81ebdd856894563c335fffa83):

Brilliant, thanks!
